version: '2'
services:
 
  user:
    build: './user'
    container_name: user_service
    ports:
      - "3000:3000"
      links:
        -db:db
    depends_on: 
      - db
    environment:
      - DATABASE_HOST=db


  sensor:
    build: './sensor'
    ports:
      - "3002:3002"
      links:
        -db:db
    depends_on: 
      - db
    environment:
      - DATABASE_HOST=db
  
  db:
    image: mongo
    ports:
      - "27017:27017"

    # depends_on:
    #   - user
    #   - sensor